package app

import (
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	tea "charm.land/bubbletea/v2"
	"gopkg.in/yaml.v3"

	"github.com/cmdux/liner/packages/go-tui/internal/core"
	sourcepkg "github.com/cmdux/liner/packages/go-tui/internal/source"
	"github.com/cmdux/liner/packages/go-tui/internal/tape"
)

type sourceRecoveryResult struct {
	Attempted int
	Succeeded int
	Failed    int
	Sources   []sourceRecoverySource
}

type sourceRecoverySource struct {
	URL     string `yaml:"url"`
	Type    string `yaml:"type"`
	Status  string `yaml:"status"`
	Reason  string `yaml:"reason,omitempty"`
	SavedTo string `yaml:"saved_to,omitempty"`
	Message string `yaml:"message,omitempty"`
}

type sourceRecoveryDoneMsg struct {
	result sourceRecoveryResult
	err    error
}

type sourceRecoveryReport struct {
	Updated   string                 `yaml:"updated"`
	Attempted int                    `yaml:"attempted"`
	Succeeded int                    `yaml:"succeeded"`
	Failed    int                    `yaml:"failed"`
	Sources   []sourceRecoverySource `yaml:"sources"`
}

var recoverySlugPattern = regexp.MustCompile(`[^a-z0-9]+`)

func (m Model) hasDroppedCustomSources() bool {
	return len(readDroppedCustomURLSources(m.currentPath, m.currentTape)) > 0
}

func (m Model) retryExcludedLocalSources() (Model, tea.Cmd) {
	if m.sourceRecoveryRunning {
		m.err = "Excluded local source retry is already running."
		return m, nil
	}
	sources := readDroppedCustomURLSources(m.currentPath, m.currentTape)
	if len(sources) == 0 {
		m.err = "No excluded local URL sources are available to retry."
		return m, nil
	}
	m.err = ""
	m.note = fmt.Sprintf("Retrying %d excluded local source(s).", len(sources))
	m.sourceRecovery = nil
	m.sourceRecoveryError = ""
	m.sourceRecoveryRunning = true
	m.sourceRecoveryReview = false
	m.compileLines = append(m.compileLines, fmt.Sprintf("Retrying %d excluded local source(s) without rebuilding the corpus.", len(sources)))
	project := m.currentPath
	runner := m.runner
	current := m.currentTape
	return m, func() tea.Msg {
		result, err := runDroppedCustomSourceRecovery(runner, project, current, sources)
		return sourceRecoveryDoneMsg{result: result, err: err}
	}
}

func runDroppedCustomSourceRecovery(runner core.Runner, project string, current tape.Tape, sources []droppedCustomSource) (sourceRecoveryResult, error) {
	result := sourceRecoveryResult{Attempted: len(sources)}
	if len(sources) == 0 {
		return result, nil
	}

	tempDir, err := os.MkdirTemp("", "liner-source-recovery-*")
	if err != nil {
		return result, err
	}
	defer os.RemoveAll(tempDir)

	retryTape := tape.Tape{
		Title:       fallbackText(current.Title, "Excluded local source retry"),
		Description: "Temporary source availability check generated by Liner.",
		Version:     1,
		Curator:     fallbackText(current.Curator, "Liner"),
		Sources:     droppedCustomTapeSources(sources),
	}
	if err := tape.WriteProject(tempDir, retryTape); err != nil {
		return result, err
	}
	if err := os.WriteFile(filepath.Join(tape.ProjectAt(tempDir).Path, "synthesis.md"), []byte("# Excluded local source retry\n\nTemporary compile used only to fetch excluded local sources.\n"), 0o644); err != nil {
		return result, err
	}

	var payload *core.CompileResultPayload
	err = runner.CompileStream(tempDir, func(event core.CompileEvent) {
		if event.Payload != nil {
			payload = event.Payload
		}
	})
	if err != nil && !isExpectedRecoveryCompileExit(err) {
		return result, err
	}
	if payload == nil {
		if err != nil {
			return result, err
		}
		return result, errors.New("excluded local source retry did not return a compile result")
	}

	result.Attempted = payload.Summary.Total
	result.Succeeded = payload.Summary.Succeeded
	result.Failed = payload.Summary.Failed
	result.Sources = recoverySourcesFromPayload(payload, sources)
	if result.Succeeded > 0 {
		if err := saveRecoveredSourceCopies(project, payload, sources, &result); err != nil {
			return result, err
		}
	}
	if err := writeSourceRecoveryReport(project, result); err != nil {
		return result, err
	}
	return result, nil
}

func droppedCustomTapeSources(sources []droppedCustomSource) []tape.Source {
	out := make([]tape.Source, 0, len(sources))
	for _, source := range sources {
		src := source.Item.Source
		if src.Priority == "" {
			src.Priority = "required"
		}
		out = append(out, src)
	}
	return out
}

func recoverySourcesFromPayload(payload *core.CompileResultPayload, sources []droppedCustomSource) []sourceRecoverySource {
	byURL := map[string]droppedCustomSource{}
	for _, source := range sources {
		byURL[normalizeRecoveryURL(source.Item.Source.URL)] = source
	}
	rows := make([]sourceRecoverySource, 0, max(len(payload.Sources), len(payload.Warnings)))
	for _, source := range payload.Sources {
		retried := byURL[normalizeRecoveryURL(source.URL)]
		status := "failed"
		if source.Succeeded {
			status = "recovered"
		}
		rows = append(rows, sourceRecoverySource{
			URL:    source.URL,
			Type:   fallbackText(source.Type, retried.Item.Source.Type),
			Status: status,
			Reason: retried.Reason,
		})
	}
	seen := map[string]bool{}
	for _, row := range rows {
		seen[normalizeRecoveryURL(row.URL)] = true
	}
	for _, warning := range payload.Warnings {
		key := normalizeRecoveryURL(warning.URL)
		if seen[key] {
			continue
		}
		retried := byURL[key]
		rows = append(rows, sourceRecoverySource{
			URL:     warning.URL,
			Type:    retried.Item.Source.Type,
			Status:  "failed",
			Reason:  retried.Reason,
			Message: warning.Message,
		})
	}
	return rows
}

func saveRecoveredSourceCopies(project string, payload *core.CompileResultPayload, sources []droppedCustomSource, result *sourceRecoveryResult) error {
	retried := map[string]droppedCustomSource{}
	for _, source := range sources {
		retried[normalizeRecoveryURL(source.Item.Source.URL)] = source
	}
	items := readLocalSourceManifest(project)
	recoveredByURL := map[string]string{}
	for _, record := range payload.Sources {
		if !record.Succeeded {
			continue
		}
		original, ok := retried[normalizeRecoveryURL(record.URL)]
		if !ok {
			continue
		}
		sourcePath := record.Path
		if !filepath.IsAbs(sourcePath) {
			sourcePath = filepath.Join(filepath.Dir(payload.MixtapePath), sourcePath)
		}
		data, err := os.ReadFile(sourcePath)
		if err != nil {
			return err
		}
		rel := recoveredSourceRelPath(original.Item.Source, record)
		abs := projectAbsPath(project, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(abs, data, 0o644); err != nil {
			return err
		}
		recoveredByURL[normalizeRecoveryURL(record.URL)] = rel
		updateRecoveryResultSavedPath(result, record.URL, rel)
		items = replaceRecoveredManifestSource(items, original.Item.Source.URL, rel, record)
	}
	if len(recoveredByURL) == 0 {
		return nil
	}
	return sourcepkg.WriteManifests(project, items)
}

func replaceRecoveredManifestSource(items []sourcepkg.StagedSource, originalURL string, rel string, record core.CompiledSourceRecord) []sourcepkg.StagedSource {
	originalKey := normalizeRecoveryURL(originalURL)
	for i := range items {
		if normalizeRecoveryURL(items[i].Source.URL) == originalKey {
			items[i].Active = false
			items[i].Status = "recovered"
		}
	}
	for i := range items {
		if items[i].Source.Path != nil && filepath.ToSlash(*items[i].Source.Path) == rel {
			items[i].Active = true
			items[i].Status = "ready"
			return items
		}
	}
	citation := recoveryCitation(record)
	note := "Recovered from excluded local source: " + originalURL
	src := tape.Source{
		Type:     "local_file",
		Path:     &rel,
		Citation: &citation,
		Note:     &note,
		Priority: "required",
	}
	staged := sourcepkg.Stage([]tape.Source{src}, true)
	return append(items, staged...)
}

func updateRecoveryResultSavedPath(result *sourceRecoveryResult, sourceURL string, rel string) {
	key := normalizeRecoveryURL(sourceURL)
	for i := range result.Sources {
		if normalizeRecoveryURL(result.Sources[i].URL) == key {
			result.Sources[i].SavedTo = rel
			return
		}
	}
}

func recoveredSourceRelPath(src tape.Source, record core.CompiledSourceRecord) string {
	slug := recoverySlug(record.URL)
	if record.Title != nil && strings.TrimSpace(*record.Title) != "" {
		slug = recoverySlug(*record.Title)
	}
	if slug == "" {
		slug = "recovered-source"
	}
	hash := sha1.Sum([]byte(fallbackText(record.URL, src.URL)))
	return filepath.ToSlash(filepath.Join("local-sources", "recovered", slug+"-"+hex.EncodeToString(hash[:])[:8]+".md"))
}

func recoveryCitation(record core.CompiledSourceRecord) string {
	if record.Title != nil && strings.TrimSpace(*record.Title) != "" {
		return strings.TrimSpace(*record.Title)
	}
	return fallbackText(record.URL, "Recovered source")
}

func recoverySlug(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	if parsed, err := url.Parse(value); err == nil && parsed.Host != "" {
		value = strings.Trim(strings.TrimPrefix(parsed.Host+parsed.Path, "www."), "/")
	}
	value = recoverySlugPattern.ReplaceAllString(value, "-")
	value = strings.Trim(value, "-")
	if len(value) > 48 {
		value = strings.Trim(value[:48], "-")
	}
	return value
}

func writeSourceRecoveryReport(project string, result sourceRecoveryResult) error {
	report := sourceRecoveryReport{
		Updated:   time.Now().Format(time.RFC3339),
		Attempted: result.Attempted,
		Succeeded: result.Succeeded,
		Failed:    result.Failed,
		Sources:   result.Sources,
	}
	data, err := yaml.Marshal(report)
	if err != nil {
		return err
	}
	path := filepath.Join(projectCorpusPath(project), "working", "source-recovery.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func isExpectedRecoveryCompileExit(err error) bool {
	var exitErr core.CompileExitError
	return errors.As(err, &exitErr) && (exitErr.Code == 2 || exitErr.Code == 3)
}

func normalizeRecoveryURL(value string) string {
	normalized := normalizeMethodologyURL(value)
	if normalized != "" {
		return normalized
	}
	return strings.TrimSpace(value)
}
