// User-level config persisted to ~/.liner/config.yaml.
//
// The shape stays an object so settings can grow without a migration. Anything
// missing from the file resolves to a safe default on read; the caller does
// not have to undefined-check.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import * as YAML from "yaml";
import type { AgentDescriptor, AgentId } from "./agents/types.js";
import type { PhaseModelMap } from "./agents/models.js";

export type UserConfig = {
  /**
   * The agent the user chose during setup. `null` means "no preference set"
   * — fall back to detection (and the mid-phase picker if multiple agents
   * are installed).
   */
  agent: AgentId | null;
  /**
   * Per-agent, per-phase model overrides. `null` (or a missing key) means
   * "use the built-in default map" — see `agents/models.ts`, which downgrades
   * the heavy phases (candidates + evaluation) to a cheaper model. Set a phase
   * here to a flagship model to undo that downgrade, e.g.
   * `models: { claude: { candidates: opus } }`.
   */
  models: Partial<Record<AgentId, PhaseModelMap>> | null;
  /**
   * Whether the first-run onboarding has already offered to install JS
   * rendering support (Playwright's Chromium download). This records the
   * prompt, not whether Chromium is currently installed; compile still detects
   * a missing browser and offers repair when a page needs it.
   */
  jsSetupPrompted: boolean;
};

const KNOWN_AGENT_IDS: readonly AgentId[] = ["claude", "codex"];

/**
 * Best-effort parse of the `models` config block. Anything that isn't a
 * `{ agent: { phase: string } }` shape is dropped silently — a malformed
 * override should never crash the TUI or block a run, just fall back to the
 * default map.
 */
function parseModels(
  raw: unknown,
): Partial<Record<AgentId, PhaseModelMap>> | null {
  if (!raw || typeof raw !== "object") return null;
  const out: Partial<Record<AgentId, PhaseModelMap>> = {};
  for (const agentId of KNOWN_AGENT_IDS) {
    const block = (raw as Record<string, unknown>)[agentId];
    if (!block || typeof block !== "object") continue;
    const phaseMap: PhaseModelMap = {};
    for (const [phase, model] of Object.entries(block as Record<string, unknown>)) {
      if (typeof model === "string") phaseMap[phase as keyof PhaseModelMap] = model;
    }
    if (Object.keys(phaseMap).length > 0) out[agentId] = phaseMap;
  }
  return Object.keys(out).length > 0 ? out : null;
}

const CONFIG_DIR = join(homedir(), ".liner");
const CONFIG_PATH = join(CONFIG_DIR, "config.yaml");

export function configPath(): string {
  return CONFIG_PATH;
}

export function configExists(): boolean {
  return existsSync(CONFIG_PATH);
}

/**
 * Read the user-level config. Returns a fully-populated config with `null`
 * defaults for any field that's missing or malformed — callers don't have
 * to undefined-check. Never throws; a corrupt config file degrades to "no
 * preference set" rather than crashing the TUI.
 */
export function readConfig(): UserConfig {
  if (!existsSync(CONFIG_PATH)) {
    return { agent: null, models: null, jsSetupPrompted: false };
  }
  try {
    const raw = YAML.parse(readFileSync(CONFIG_PATH, "utf8")) as
      | Record<string, unknown>
      | null;
    if (!raw || typeof raw !== "object") {
      return { agent: null, models: null, jsSetupPrompted: false };
    }
    const agent = raw["agent"];
    const validAgent: AgentId | null =
      agent === "claude" || agent === "codex" ? agent : null;
    return {
      agent: validAgent,
      models: parseModels(raw["models"]),
      jsSetupPrompted: raw["jsSetupPrompted"] === true,
    };
  } catch {
    return { agent: null, models: null, jsSetupPrompted: false };
  }
}

/**
 * Persist a config patch, merged over whatever is already on disk. Callers
 * that only touch one field (e.g. the agent picker) leave the rest — including
 * hand-edited model overrides — intact.
 */
export function writeConfig(patch: Partial<UserConfig>): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true });
  }
  const current = readConfig();
  const merged: UserConfig = {
    agent: patch.agent !== undefined ? patch.agent : current.agent,
    models: patch.models !== undefined ? patch.models : current.models,
    jsSetupPrompted:
      patch.jsSetupPrompted !== undefined
        ? patch.jsSetupPrompted
        : current.jsSetupPrompted,
  };
  // Stable, hand-editable output. Comment at the top so curators who poke at
  // the file know what's there and how to extend it.
  const body = [
    "# Liner user config — generated by the TUI.",
    "# Hand-edit if you know what you want; the TUI rewrites supported",
    "# settings when they change.",
    "#",
    "# models: per-agent, per-phase model overrides. The heavy phases",
    "#   (candidates, evaluation) default to a cheaper model — set them back to",
    "#   a flagship model here to undo that, e.g.:",
    "#     models:",
    "#       claude:",
    "#         candidates: opus",
    "#         evaluation: opus",
    "# jsSetupPrompted: true after the first-run JS rendering prompt has shown.",
    "",
    YAML.stringify(merged),
  ].join("\n");
  writeFileSync(CONFIG_PATH, body, "utf8");
}

/**
 * Pick which agent to use. Returns null when no agents are available at all.
 * Priority order:
 *   1. LINER_AGENT env var (escape hatch for CI / power users)
 *   2. The configured agent in ~/.liner/config.yaml, IF it's installed
 *   3. The single installed agent (when only one is available)
 *   4. null — caller should show a picker
 */
export function resolveConfiguredAgent(
  installed: AgentDescriptor[],
  config: UserConfig = readConfig(),
): AgentDescriptor | null {
  if (installed.length === 0) return null;

  const envPin = (process.env["LINER_AGENT"] || "").toLowerCase();
  if (envPin) {
    const pinned = installed.find((a) => a.id === envPin);
    if (pinned) return pinned;
    // Env names an agent that isn't installed — fall through to the
    // configured / auto-pick path rather than crashing.
  }

  if (config.agent) {
    const configured = installed.find((a) => a.id === config.agent);
    if (configured) return configured;
    // The configured agent isn't installed anymore (user uninstalled it).
    // Fall through; the caller will either pick the remaining one or
    // re-prompt setup.
  }

  if (installed.length === 1) {
    return installed[0]!;
  }

  return null;
}
